### ISSUE TITLE
Too long, buried the lede

### ISSUE THREAD

**Issue by alexgriff** [learn-co-curriculum/js-basics-functions-readme#1]
The whole beginning of this is great, and I think does a good job showing the point of using functions, but they don't know what a function is yet! 

Seems like this could be moved to a subsequent code along 'Using Functions for Legibility and Encapuslation' or 'Refactoring with Functions'.

I would imagine another utility of the labs/readings is a place for students to go and refer back to to review. Looking back at this reading it's hard to find the new (and very important) content.

I would suggest a standalone reading like 'what is a function', very short to the point. A unit of work, a little procedure, etc

ex:
```js
function double(num) {
 return num * 2
}
double(5)
// => 10
```
 There are so many super foundational things here. What's a return value and why? Understanding the abstraction of like we totally could write `5 * 2` or `10 * 2` but we have encapsualted that logic into a single unit of work and made it abstract. Created a little machine, we feed it inputs, gives outputs. 

This lab covers exactly these points, but they get lost here i think. I know we usually like to show the pain first and then reveal a solution, but this is just so foundational I think we need to give it a spotlight and then supply the context.

**Comment by gj** [comment]
@alexgriff Very valid critique — I agree it's too long. I'm hesitant to flip the narrative around and introduce the concept outside of the context (pain), but maybe we could start w/ something like this:

<img width="243" alt="screen shot 2017-10-05 at 2 27 36 pm" src="https://user-images.githubusercontent.com/17556281/31245816-83b60220-a9d9-11e7-846f-7925feea7dba.png">

thoughts @jmburges ?

**Comment by itzsaga** [comment]
Going through the new JS curriculum as a grad to refresh and I must agree that this lesson is LONG.

**Comment by sgharms** [comment]
Hi, i've punched it up. 086cb85
