### ISSUE TITLE
Error in readme: Mozart is a classical-era (not baroque-era) composer.

### ISSUE THREAD

**Issue by nicolefederici** [learn-co-curriculum/js-basics-functions-readme#11]
This is the sentence in Learn:
"We also use abstractions to decide what doesn't fit or what should fit. "Mozart" doesn't belong with The Beatles, but he does fit with "Baroque Masters.""   It should read "classical masters" instead. 

Mozart is not a baroque-era composer. He is a classical-era composer. The two periods are very different, kinda like saying that Linus Torvalds is from the same era as Turing or the Beatles are from the same era as Cardi B. (except it's worse, because Mozart (1756 – 1791) was born after Bach (1685 – 1750) had died and Paul Mc Cartney is still alive and making music during the same era as Cardi B.)
The baroque period is about religious music, ornate decoration and counterpoint, and the classical era is about science, reason, enlightenment and minimalism and essentialism in music. Its cleanlines are the opposite of baroque. The classical composers also had musical instrument technology the baroque composers lacked. Anyhow, the Baroque era is generally understood to be mostly over with the death of JS Bach. Likewise, Mozart is kinda the pinnacle of the classical period- he positively defines it if any composer does. Beethoven picks up the torch there from Mozart (he was a teeny tiny bit classical at first) and takes us into the romantic era with his innovations.  

I tried to create a pull request for this using bash and that stuff I have learned, but I think I just ended up pushing it to myself. I asked for help so I could learn how to create a pull request to your repo, but I was told to just do this. Perhaps this is a pull request in itself? Hope I helped.

**Comment by sgharms** [comment]
Your keen eye is noted. Correction made.

I also applaud your detailed consideration of our example domain. It's difficult to find something that works globally that's not a commercial juggernaut (side-eye, JK Rowling).

**Comment by sgharms** [comment]
@nicolefederici Also, I applaud your attempt to make a PR against this. Schedule some time with a coach to say you want to focus on making PRs.
