### ISSUE TITLE
Missing "of" in this sentence

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/js-basics-functions-readme#12]
"A function is an object that contains a sequence JavaScript statements."

should be

"A function is an object that contains a sequence of JavaScript statements."

Thank you.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
