### ISSUE TITLE
Sequence issue

### ISSUE THREAD

**Issue by curlywallst** [learn-co-curriculum/js-basics-functions-readme#3]
The previous lab "Control Flow Lab" asks the student to write 3 functions.  This lab teaches how to write a function.  I think this lab should come before the last one

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @curlywallst.

We have updated the previous control flow lab and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
