### ISSUE TITLE
out of order?

### ISSUE THREAD

**Issue by ddbrennan** [learn-co-curriculum/js-basics-functions-readme#4]
we had to write functions in the previous lab

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @ddbrennan.

We have updated the previous control flow lab and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
