### ISSUE TITLE
Spelling/Grammar error in code

### ISSUE THREAD

**Issue by arianaberger** [learn-co-curriculum/js-basics-functions-readme#9]
function exerciseDog(dogName, dogBreed) {
  console.log(`Wake ${dogName} the ${dogBreed}`);
  console.log(`Leash ${dogName} the ${dogBreed}`);
  console.log(`Walk to the park ${dogName} the ${dogBreed}`);
  console.log(`Throw the fribsee for ${dogName} the ${dogBreed}`);
  console.log(`Walk home with ${dogName} the ${dogBreed}`);
  console.log(`Unleash Byron ${dogName} ${dogBreed}`);
}

The last line should be changed to:

console.log(`Unleash ${dogName} the ${dogBreed}`);
}

**Comment by sgharms** [comment]
Thank you! Byron thanks you, too.


![img_0989](https://user-images.githubusercontent.com/50019/47962833-a5b44500-dff0-11e8-9fce-7838826e11b4.jpeg)
